# -*- coding: utf-8 -*-
"""HomeWorkTask

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DfoEeVnyyld7WysYmNDnAlwnW7amhElC
"""

# Задача 1.1

# Первый трек
my_favorite_songs = ' , '
first_song = my_favorite_songs.split(',')[0]
print(first_song) # Выводит первый трек из списка
# Последний трек
last_song = my_favorite_songs.split(',')[-1]
print(last_song) # Выводит последний трек из списка
# Второй трек
second_song = my_favorite_songs.split(',')[1]
print(second_song) # Выводит второй трек из списка
# Предпоследний трек
second_last_song = my_favorite_songs.split(',')[-2]
print(second_last_song) # Выводит предпоследний трек из списка